apiVersion: v2
name: service-a                      # ✅ REQUIRED: name of the chart
description: Helm chart for service-a microservice
version: 0.1.0                       # ✅ REQUIRED: chart version
appVersion: "1.0.0"                  # Optional: version of your app




# this file defines the identity and versioning of your Helm chart. It’s required for Helm to recognize, validate, and manage your chart