apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
spec:
  validationFailureAction: enforce
  rules:
    - name: check-app-label
      match:
        resources:
          kinds:
            - Deployment
      validate:
        message: "app label is required"
        pattern:
          metadata:
            labels:
              app: "?*"
